### ISSUE TITLE
Correct pin connections for USBasp

### ISSUE THREAD

**Issue by GKnirps** [MrMoDDoM/MuTag#1]
Hi,
I got a MuTag at the Chaos Communication Camp last year and I finally found some time to play around with it.

On [this page](https://muhack.org/events/CCC23-landing-page/), you say I can also use a [USBasp](https://www.fischl.de/usbasp/) for programming the tag. This is convenient because I already have one of those.

However, I'm a bit at a loss of which pins to connect. For the Arduino solution, the readme files lists the correct connections but I cannot find anything about the USBasp.

Can someone help me out here?

**Comment by MrMoDDoM** [comment]
Hi!
The USBasp should have a set of MISO/MOSI as well clock and reset pins.

Depending on your version, you should be able to access the 6Pin header on your board ( https://www.datasheetcafe.com/usbasp-pinout-avr-programmer/ ) 

Then simply match the data line name ;)

| USBasp | MuTag |
|--------|----------|
|    VCC    |    VCC      |
|     GND   |    GND   |
|  SCK | SCK |
| RST | RST |
| MISO | MISO |
| MOSI | MOSI |

**Comment by GKnirps** [comment]
Hi,
thanks for the reply!

I don't have the 6-Pin header on my USBAsp. I can probably map the 10 pin output (which has only 8 unique connections), but I am unsure with some of them.

I can find GND, SCK, MISO, and MOSI, but I am unsure where RST and VCC go. The schema you send me looks slightly different from the one I have on my device. I assume VCC is the power supply, and RST is reset? I'm not really familiar with these abbreviations.

**Comment by MrMoDDoM** [comment]
Yes, you are correct, the VCC is the 5v power line, and RST is the indeed reset :)
The only two line you should double check are the VCC and GND (ground) ones, as they can damage the Tag if connected wrongly.. you can mess up how much you want the other line, they can not do any harm ;)

As before, simply match the line name between the Tag and the USBasp, using the 10 pin header is fine.

**Comment by GKnirps** [comment]
Thanks again. I have not been able to do anything with the tag yet because I don't have the appropriate cables actually connect it to the USBAsp (to be fair, I don't even know what I should use, nothing really sticks in there), but the pin layout is now pretty clear, so I'll close this ticket.

**Comment by MrMoDDoM** [comment]
Hi, to clarify a little bit more, you can also use an Arduino to program the Tag, the USBAsp is compatible as well but maybe a little too complicated to use..
If you have difficulties, I can assist you with step-by-step guidance: the procedure is the same as using an Arduino as ISP Programmer ( https://docs.arduino.cc/built-in-examples/arduino-isp/ArduinoISP/ ), you can also find countless tutorial and video on how to program a target MCU (in our case the MuTag) with this procedure https://www.youtube.com/watch?v=TtC6crf_EP4

**Comment by GKnirps** [comment]
Thanks, I will get back to you when I run into problems!
